<a href="https://colab.research.google.com/github/erika1013/Almacenamineto-v1/blob/master/1_libraries_blank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python para análisis de datos


Para iniciar con python se recomienda instalar [ANACONDA](https://www.continuum.io/downloads) , en la version de python 3.9 o superior

---


**Nota** Despues de instalado se puede cambiar de version siguiendo los  [pasos](http://conda.pydata.org/docs/py2or3.html) , [ayuda](http://stackoverflow.com/questions/30492623/using-both-python-2-x-and-python-3-x-in-ipython-notebook)
---


## Verifiquemos que tenemos lo que necesitamos

In [ ]:
#@title
# Python version
import sys
print('Python: {}'.format(sys.version))

import sklearn
print('sklearn: {}'.format(sklearn.__version__))
# scipy
import scipy
print('scipy: {}'.format(scipy.__version__))
# numpy
import numpy
print('numpy: {}'.format(numpy.__version__))
# matplotlib
import matplotlib
print('matplotlib: {}'.format(matplotlib.__version__))
# pandas
import pandas
print('pandas: {}'.format(pandas.__version__))
# scikit-learn
import sklearn
print('sklearn: {}'.format(sklearn.__version__))



## Buscar ayuda
Tenemos la opción de usar ? para ver la ayuda de una función, o usar tab para ver las funciones disponibles de un objeto

Ejercicio: importar la biblioteca random y buscar ayuda sobre la función `random`



In [ ]:
import random
random.randint





# Python
Python es un lenguaje de programación de alto nivel, interpretado, interactivo, orientado a objetos y de propósito general. Fue creado por Guido van Rossum durante 1985-1990. Al igual que Perl, el código fuente de Python también está disponible bajo la Licencia Pública General de GNU (GPL).


- se considera la mejor práctica ([PEP8](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names)) que los nombres de las variables están en minúsculas con guiones bajos
- Python utiliza *escritura dinámica*, lo que significa que puede reasignar variables a diferentes tipos de datos.
- Python soporta cuatro tipos numéricos diferentes

  - int (enteros con signo) `5`
  - long (enteros largos, también se pueden representar en octal y hexadecimal) `5L`,` 0x80`
  - float (valores reales de punto flotante) `0.0`,` 0.5e52`
  - complejo (números complejos) `14.5j`
- Se puede pensar en las listas de la versión más general de una secuencia en Python. A diferencia de las cadenas, son mutables, lo que significa que los elementos dentro de una lista se pueden cambiar.
- Lo importante de una lista es que los elementos de una lista no tienen que ser del mismo tipo.
- Una gran característica de las estructuras de datos de Python es que admiten el anidamiento. Esto significa que podemos tener estructuras de datos dentro de estructuras de datos
-En las estructuras de datos Diccionario([dict](https://docs.python.org/3/tutorial/datastructures.html)) Las claves son únicas dentro de un diccionario, mientras que los valores pueden no serlo.
- Los valores de un diccionario pueden ser de cualquier tipo, pero las claves deben ser de un tipo de datos inmutables como cadenas, números o tuplas.
- En Python, la TUPLA es otro tipo de arreglo que dispone el Python. Esta variable está más cerca al concepto matemático de vector, puesto que en Python la tupla se maneja como una lista más cerrada porque no puede cambiar elementos individuales, en otras palabras, es inmutable según lo definen [tuples](https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences)


Un buen punto de partida es descargar un resumen del tema de busqueda esta pagina presenta excelentes resumenes de python [Python Crash Course, Second Edition](https://ehmatthes.github.io/pcc_2e/cheat_sheets/cheat_sheets/), el cual es resumen de un muy buen [libro](https://nostarch.com/pythoncrashcourse2e)

In [ ]:
2**3



8


## Python basico


Sin ejecutar el codigo, que crees que retorna cada item? pruebalo

1. **numbers**

```
3/2
3/float(2)
3%2
3.00//2.00
2**3
4**0.5
import math
math.sqrt(4)
2 + 10 * 10 + 3
(2+10) * (10+3)
```
2. **Variables**

```
a = 10
a =a + 10
a += 10
b = c = a
a,b,c = 1,2,"john"
my_dogs = 2
my_dogs = ['Sammy', 'Frankie']
del my_dogs

```
3. **string**

```
str = 'Hello World!'

print (str)          
print (str[0])       
print (str[2:5])     
print (str[2:])      
print (str * 2)      
print (str + "TEST")
str.upper()
str.split()
'Carlos: {}'.format(str)
print(" %s ,  %s" %(str,"I'm Carlos"))

print('I wrote %s programs today.' %3.75)
print('I wrote %d programs today.' %3.75)
print('I wrote %5.2f programs today.' %3.75)
print('First: %s, Second: %5.2f, Third: %r' %('hi!',3.1415,'bye!'))
print('The {2} {1} {0}'.format('fox','brown','quick'))
print('First Object: {a}, Second Object: {b}, Third Object: {c}'.format(a=1,b='Two',c=12.3))

print('{0:8} | {1:9}'.format('Fruit', 'Quantity'))
print('{0:8} | {1:9}'.format('Apples', 3.))
print('{0:8} | {1:9}'.format('Oranges', 10))

print(f'I wrote {3.75:.1f} programs today.')
print(f'First:{"hi!"}, Second: {3.1415:.2}, Third: {3}')

```

4. **Array list**

```
my_list = [1,2,3]
my_list = ['A string',23,100.232,0]
my_list + ['new item']
my_list = my_list +['new item']
my_list.pop(0)
my_list.pop(-1)
my_list.reverse()
my_list.sort()
my_list * 2
my_list=[]
my_list=array()

num_list = range(1, 101)
print(num_list[49])
type(num_list)
len(num_list)

new_list = [0, 1, 2, 3, 4, 5, 6]
new_list[2] = 2001;
new_list[2:5]
new_list[:3]
new_list[-2:]

list_1 = [1,2]
list_2 = [3, 4]
list_1=list_1+list_2
list_1.append(list_2)
[num*2 for num in list_1]

lst_1=[1,2,3]
lst_2=[4,5,6]
lst_3=[7,8,9]
matrix = [lst_1,lst_2,lst_3]
matrix[0][0]=8
print(matrix)

```
4.  **Dictionary**

```
d = {'a':10, 'b':20, 'c':30}
d['a']
d['b']=40
d.clear()

print(d)

dict = {'Name': 'Zara', 'Age': 7, 'Name': 'Manni'}
dict.values()
dict.keys()
dict.items()
print(dict['Name'])
dict2['Name']='Carlos'
dict.update(dict2)


locations = {'Sinan': ['Baltimore', 'MD'], 'Brandon': ['Arlington', 'VA']}
print(locations['Brandon'][1])

from numpy import random
data = {f'a{i}' : random.randn() for i in range(7)}
print(data['a1'])
data
```

5. ** functions**

```
def calc(a, b):
    return a + b
print(calc(2,3))
```

Para probar cualquiera de los códigos anteriores, simplemente copie el bloque de código en la celda de python a continuación.

![numpy](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/640px-NumPy_logo.svg.png)


## Numpy


NumPy es el paquete fundamental para la computación científica con Python. Contiene entre otras cosas:

- un poderoso objeto de matriz N-dimensional

-funciones sofisticadas (de transmisión)

- herramientas para integrar código C / C ++ y Fortran

- Álgebra lineal útil, transformada de Fourier y capacidades de números aleatorios


Todo Arreglo/array en Numpy es tratado como un objeto que entre sus propiedades tiene:

- ndarray.ndim –> Proporciona el número de dimensiones de nuestro array. El array identidad es un array cuadrado con una diagonal principal unitaria.
- ndarray.shape –> Devuelve la dimensión del array, es decir, una tupla de enteros indicando el tamaño del array en cada dimensión. Para una matriz de n filas y m columnas obtendremos (n,m).
- ndarray.size –> Es el número total de elementos del array.
- ndarray.dtype –> Es un objeto que describe el tipo de elementos del array.
- ndarray.itemsize –> devuelve el tamaño del array en bytes.
- ndarray.data –> El buffer contiene los elementos actuales del array.

## Creación de Arrays


- identity(n,dtype). Devuelve la matriz identidad, es decir, uma matriz cuadrada nula excepto en su diagonal principal que es unitaria. n es el número de filas (y columnas) que tendrá la matriz y dtype es el tipo de dato. Este argumento es opcional. Si no se establece, se toma por defecto como flotante.
- ones(shape,dtype). Crea un array de unos compuesto de shape elementos.
- zeros(shape, dtype). Crea un array de ceros compuesto de “shape” elementos”.
- empty(shape, dtype). Crea un array de ceros compuesto de “shape” elementos” sin entradas.
- eye(N, M, k, dtype). Crea un array bidimensional con unos en la diagonal k y ceros en el resto. Es similar a identity. Todos los argumentos son opcionales. N es el número de filas, M el de columnas y k es el índice de la diagonal. Cuando k=0 nos referimos a la diagonal principal y por tanto eye es similar a identity.
- arange([start,]stop[,step,],dtype=None). Crea un array con valores distanciados step entre el valor inicial star y el valor final stop. Si no se establece step python establecerá uno por defecto.
- linspace(start,stop,num,endpoint=True,retstep=False). Crea un array con valor inicial start, valor final stop y num elementos.
- meshgrid(x,y). Genera una matriz de coordenadas a partir de dos los arrays x, y.

## Funciones

El módulo numpy contiene todas las operaciones usuales entre arrays como las matemáticas (suma, resta, multiplicación, etc), las lógicas (and, or, xor, etc), binarias, ...
[Operaciones Numpy](https://drive.google.com/file/d/17wZqpCvckCb8Ous3HAaRqPu33rJKtTeB/view?usp=sharing)



Lo más fácil y sencillo es en caso de duda consultar la documentación oficial. [documentacion](https://docs.scipy.org/doc/numpy/reference/index.html#reference)




In [ ]:
import numpy as np # Importamos numpy como el alias np

In [ ]:

# tipo de datos
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
#funciones basicas
miArray = np.arange(10) # Creamos un array de 0 a 9 separados de uno en uno
print (miArray) # Presentamos en pantalla el array creado
print (type(miArray))   #Comprobamos que es un ndarray
print (miArray.ndim )   # Consultamos el número de dimensiones
print (miArray.shape )  # Consultamos la dimensión
print (miArray.size )  # Consultamos la dimensión
print (miArray.dtype )  # Consultamos el tipo de elementos del array
print (miArray.itemsize )  # tamaño en bytes
print (miArray.data )  # Consultamos el buffer de memoria.



[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(10,)
10
int64
8


In [ ]:
# array bidimensionales
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2d[2])

print(arr2d[0][2])
#arr2d[0,2]

#grupo de elementos
print((arr2d[:,1]))

# acesso con operaciones
print(arr2d[arr2d>4])

#fancy indexing (una matrix es en verdad un arreglo)
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
print(arr)

#seleccionar columnas en desorden
print (arr[[4, 3, 0, 6]])
#Using negative indices select rows from the end
print(arr[[-3, -5, -7]])

#reorganizar vectores
arr = np.arange(32).reshape((8, 4))
print(arr)

[7 8 9]
3
[2 5 8]
[5 6 7 8 9]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]
[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


### **Ejercicio**

Crear dos vectores de diez numeros aleatorios enteros [np.random.randint](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html) entre 1 y 10 y realizar las siguientes operaciones:
- sumarlos
- concatenar los dos arreglos
- encontrar la sumatoria de los valores
- encontrar la media de los valores
- imprimir los numeros mayores que 5
- determinar las posiciones de los numeros que son iguales en los arreglos



In [ ]:
import numpy as np

# Vectores de diez números aleatorios enteros en el rango de 1 a 10
vector1 = np.random.randint(1, 11, size=10)
vector2 = np.random.randint(1, 11, size=10)

# Sumar los dos vectores
resultado_suma = vector1 + vector2

# Concatenar los dos arreglos
resultado_concatenacion = np.concatenate((vector1, vector2))

# Encontrar la sumatoria de los valores
sumatoria_valores = np.sum(resultado_concatenacion)

# Encontrar la media de los valores
media_valores = np.mean(resultado_concatenacion)

# Imprimir los números mayores que 5
numeros_mayores_que_5 = resultado_concatenacion[resultado_concatenacion > 5]

# Determinar las posiciones de los números que son iguales en los arreglos
posiciones_iguales = np.where(vector1 == vector2)

# Mostrar los resultados
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Resultado de la suma:", resultado_suma)
print("Concatenación de los dos arreglos:", resultado_concatenacion)
print("Sumatoria de los valores:", sumatoria_valores)
print("Media de los valores:", media_valores)
print("Números mayores que 5:", numeros_mayores_que_5)
print("Posiciones de números iguales:", posiciones_iguales)



Vector 1: [9 6 1 6 7 4 6 9 5 1]
Vector 2: [ 2  4  9  8  9  2  5 10  1 10]
Resultado de la suma: [11 10 10 14 16  6 11 19  6 11]
Concatenación de los dos arreglos: [ 9  6  1  6  7  4  6  9  5  1  2  4  9  8  9  2  5 10  1 10]
Sumatoria de los valores: 114
Media de los valores: 5.7
Números mayores que 5: [ 9  6  6  7  6  9  9  8  9 10 10]
Posiciones de números iguales: (array([], dtype=int64),)


## SQLite

Cuando abre un excel o CSV en Python y lo asigna a un nombre de variable, está usando la memoria de su computadora para guardar esa variable. Acceder a los datos desde una base de datos como SQL no solo es más eficiente, sino que también le permite importar solo las partes de los datos que necesita.


Cada una de las bases de datos tienen sus librerias para python, a manera de ejemplo veamos SQLite.

- Revisar la base de datos en linea [sqliteonline](https://sqliteonline.com/)


- **Ejercicio** escribamos tres query (enunciado en [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) y luego el codigo sql respectivo.

los datos son   la Guía de valor para vehículos en Colombia suministrada por fasecolda, que se puede descargar de [Kaggle](https://www.kaggle.com/panchicore/vehicles-colombia-fasecolda/version/1)


[Link de descarga](https://drive.google.com/file/d/1wVSVbq1cJ68dU-0D8c4tPh83Hjy8azPM/view?usp=sharing)


tutorial [sqllite](http://www.datacarpentry.org/python-ecology-lesson/08-working-with-sql)


In [ ]:
# Cargamos el archivo (solo en collaborative) en caso contrario colocar el archivo en la raiz
from google.colab import files
files.upload()

In [9]:

import sqlite3

# Create a SQL connection to our SQLite database
con = sqlite3.connect("guia_fasecolda.sqlite")

cur = con.cursor()

# the result of a "cursor.execute" can be iterated over by row

#for row in cur.execute('SELECT Marca,Referencia1,Cilindraje,Peso,"2015","2016","2017" FROM carros where Cilindraje<1500 AND Cilindraje>1200 AND "2015">0;'):
  # print(row)


#AQUI Realize sus consultas sql de los datos
# Contar todos los carros con cilindraje menor igual 1200
for row in cur.execute('SELECT count(*) Cilindraje FROM carros where Cilindraje<=1200 ;'):
   print(row)

# Contar todos los carros con cilindraje menor igual 1200
for row in cur.execute('SELECT * from  carros where servicio = "Publico" and Cilindraje<=1200 ;'):
   print(row)

# Seleccionar las clases de vehiculos existentes
for row in cur.execute('SELECT distinct(Clase) from  carros;' ):
   print(row)

#Be sure to close the connection.
con.close()


(2710,)
('M', 'DINA', 'FURGON', 912001, None, 'D-7800', 'C3 [ASL]', 'MT 6X4 TD', 0, 2, 'Publico', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43700, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 141500, 176900, 1, 0, 'MT', 0, 'MEX', 2, 0, 2, 0, 3, 'Activo', 'DSL', '6X4', 0, 0)
('A', 'CHEVROLET', 'AUTOMOVIL', 1601099, None, 'SPRINT', '1.0', 'MT 1000CC TAXI', 1180, 2, 'Publico', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 1200, 1500, 1800, 2200, 2600, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17900, 20600, 0, 52, 'MT', 997, 'COL', 5, 0, 5, 0, 2, 'Activo', 'GSL', '4X2', 0, 1)
('M', 'CHEVROLET', 'AUTOMOVIL', 1601132, None, 'SPARK [1]', '7:24', 'MT 1000CC TAXI SA', 795, 2, 'Publico', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2300, 2800, 3400, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17500, 20100, 0, 62, 'MT', 995, 'COL', 5, 0, 5, 0, 2, 'Activo'

## Pandas

![Panda Logo](https://pandas.pydata.org/_static/pandas_logo.png)

Documentación de [Pandas](http://pandas.pydata.org/pandas-docs/stable/10min.html)

Pandas es una librería para el análisis de datos que cuenta con las estructuras de datos que necesitamos para limpiar los datos en bruto y que sean aptos para el análisis (por ejemplo, tablas). Es importante señalar aquí que, dado que pandas lleva a cabo tareas importantes, como alinear datos para su comparación, fusionar conjuntos de datos, gestión de datos perdidos, etc., se ha convertido en una librería muy importante para procesar datos a alto nivel en Python (es decir, estadísticas ). Pandas fue diseñada originalmente para gestionar datos financieros, y como alternativa al uso de hojas de cálculo (es decir, Microsoft Excel). Esta libreria tambien es equivalente en gran parte a las estructuras de datos de R.

La estructura de datos básica de pandas son:

- **Series**: Son arrays unidimensionales con indexación (arrays con índice o etiquetados), similar a los diccionarios. Pueden generarse a partir de diccionarios o de listas.
- **DataFrame**: Es una colección ordenada de columnas con nombres y tipos. Son estructuras de datos similares a las tablas de bases de datos relacionales como SQL, donde una sola fila representa un único caso (ejemplo) y las columnas representan atributos particulares.
- **Panel, Panel4D y PanelND**: Estas estructuras de datos permiten trabajar con más de dos dimensiones.

Sobre este tipo de estructura de datos se aplican funciones, ejemplo:


In [ ]:
import pandas as pd

dates = pd.date_range('20200101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

In [ ]:
#valores iniciales de la lista
df.head()


In [ ]:
#valores finales de la lista
df.tail(3)

In [ ]:
#aceder a los datos como un arreglo numpy
print(df.index)
print(df.columns)
df.values


In [ ]:

# acediendo ciertos datos
df['A']
df[1:3]
df[df.A > 0]

df.sort_values(by='B')



In [ ]:
# toda la estadistica descriptiva

df.describe()

Existen herramientas que permiten generar una descripción grafica y numerica automaticamente tales como:
- [sweetviz](https://github.com/fbdesignpro/sweetviz)
- [pandas profiling](https://github.com/pandas-profiling/pandas-profiling)

Estas librerias no estan por defecto instaladas en google colab o en su ambiente de trabajo, por lo cual se pueden instalar con

  *!pip install package*

In [ ]:
!pip install sweetviz
import sweetviz as sv

In [ ]:
import sweetviz as sv

my_report = sv.analyze(df)
my_report.show_notebook()

In [ ]:
!pip install ydata-profiling

In [ ]:
from ydata_profiling import ProfileReport
profile = ProfileReport(df)
profile.to_widgets()

## Comprender los datos con estadísticas descriptivas
Una vez que haya cargado sus datos en Python, debe poder entenderlos. Cuanto mejor pueda comprender sus datos, mejores y más precisos serán los modelos que puede construir.
El primer paso para comprender sus datos es utilizar estadísticas descriptivas.

### **Ejercicio**

- Realize un query sobre los datos que desea analizar con datos de precios de varios años
- Revise la distribución de sus datos con la función [describe()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.describe.html#pandas.DataFrame.describe).
- Calcule la correlación por pares entre sus variables usando la función [corr ()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.corr.html#pandas.DataFrame.corr) .

[documentación](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html)





In [ ]:
import pandas as pd
import sqlite3
from IPython.display import display, HTML

# Read sqlite query results into a pandas DataFrame
con = sqlite3.connect("guia_fasecolda.sqlite")

#ESCRIBE LA CONSULTA DE LO QUE DESEAS ANALIZAR
#df = pd.read_sql_query('SELECT Marca,Referencia1,Cilindraje,Peso,"2015","2016","2017" FROM carros where Cilindraje<1500 AND Cilindraje>1200 AND "2015">0;', con)
df = pd.read_sql_query('SELECT * FROM carros', con)

#
df1=pd.read_sql_query('SELECT * from  carros where servicio = "Publico" and Cilindraje<=1200',con)


print("Carros de servicio Publico Cilindraje <=1200",df1)
#print("Total de memoria ram requerida ",df.memory_usage().sum())


#estadistica descriptiva
display(HTML(df1.describe().to_html()))
#correlación entre las columnas
display(HTML(df1.corr().to_html()))

con.close()



Como notaste en el ejemplo anterior Pandas permite conectarse directamente a la base de datos, tambien permite leer datos en multiples formatos [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html) , por ejemplo si yo quiero cargar los datos originales de FASECOLDA

In [ ]:
# Cargamos el archivo (solo en collaborative)
from google.colab import files
files.upload()

In [ ]:

data = pd.read_csv('guia_fasecolda.csv')
print("Total de memoria ram requerida ",data.memory_usage().sum())


print(data.columns)



## Comprender los datos con visualización

Debes dedicar tiempo a comprender mejor tus datos. Una segunda forma de mejorar su comprensión de sus datos es mediante el uso de técnicas de visualización de datos . Usar la representación en Python para comprender los atributos por sí solos y sus interacciones. Ejemplos:
- Use la función hist () para crear un histograma de cada atributo.
- Use la función plot (kind = 'box') para crear diagramas de caja y cajas de cada atributo.
- Utilice la función  pandas.scatter_matrix() para crear gráficos de dispersión por pares de todos los atributos.

Es importante agregar```% inline matplotlib```  en la primera línea de su código si desea que la imagen esté incrustada en el *notebook* de Júpiter.


[pyplot](http://matplotlib.org/api/pyplot_api.html) es la mejor opción, claro que si trabajamos con Pandas, el tiene ya programada las graficas utlizando toda la información del dataset [ejemplo](https://pandas.pydata.org/pandas-docs/stable/10min.html#plotting)





### **Ejercicio**

- Cargar el dataset de Fasecolda suministrado en csv

-  Comprenda sus datos usando la función `columns` para ver las filas
-  Utilize diferentes criterios para filtrar los datos.
-  utilize por lo menos tres funciones de pandas para describir los datos filtrados
-  Guarde los datos filtrados
-  Realize por lo menos tres graficas de los datos

[Link de descarga](https://drive.google.com/file/d/1mPnVLno8uLF1bD1EQbIRVUmxk1c1BVc4/view?usp=sharing)

In [ ]:
# Load CSV using Pandas from URL
import pandas as pd
from IPython.display import display, HTML
data = pd.read_csv('guia_fasecolda.csv')

print(data.columns)

#Realiza diferentes filtros sobre los datos y guarda los datos filtrados

dataauteco = data[data.Marca=='AUTECO']
print(dataauteco.describe())
print(dataauteco.shape)

dataClase = data[(data.Clase=='CAMPERO') & (data.Marca =='LEXUS')]
print(dataClase.describe())
print(dataClase.shape)

dataPeso = data[(data.Peso==1100) & (data.Marca =='LEXUS')]
print(dataPeso.describe())
print(dataClase.shape)

#funciones de pandas para describir los datos filtrados

#Funcion dscribe
descripcion = dataPeso.describe()
print(descripcion)

#funcion info
info_dataframe = dataPeso.info()
print(info_dataframe)

#Funcion Ultimas
ultimas_filas = dataPeso.tail()
print("\nÚltimas Filas:\n", ultimas_filas)


#display(HTML((data.head().to_html())))
#print(df[data['2015']>50000])


In [ ]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt

plt.figure()
data[['Cilindraje','Peso']].plot(kind = 'box',ylim=(-1000,10000))
plt.title('mi primera grafica')
plt.show()

In [ ]:
#Realize por lo menos tres graficas de los datos
data['Cilindraje'].plot(kind='hist', bins=10, edgecolor='black')
plt.title('Histograma de Cilindraje')
plt.xlabel('Cilindraje')
plt.ylabel('Frecuencia')
plt.show()

data.groupby('Clase')['Peso'].mean().plot(kind='bar', color='skyblue')
plt.title('Promedio de Peso por Clase')
plt.xlabel('Clase')
plt.ylabel('Promedio de Peso')
plt.show()

data.groupby('Marca')['Cilindraje'].mean().plot(kind='line', marker='o', linestyle='-', color='green')
plt.title('Promedio de Cilindraje por Marca')
plt.xlabel('Marca')
plt.ylabel('Promedio de Cilindraje')
plt.show()

## Conclusiones

De acuerdo a este análisis previo de los datos sobre la base de datos de FASECOLDA, que preguntas harias de análisis de datos que puedan generar valor.
  
  * ¿Existen correlaciones entre el cilindraje y otras características técnicas como la potencia y capacidad ?    

Con que otra base de datos trabajarias para obtener valor de estos datos.
  
  * Trabajaria  con datos de  Datos.gob  Parque Automotor Activo  segmentando por departamentos o ciudades

Utilize por lo menos dos análisis del curso de estadistica y/o de visualización de datos  para este problema.

Plantea una pregunta aprendizaje supervisado y otra de supervisado que pensarias genere valor sobre este dataset

*¿Cómo predecir las emisiones de CO2 de un vehículo basándonos en el tipo   de combustible y otras características técnicas


**NOTA** Para seguir validando su nivel de conocimiento del lenguaje, comparto [esta guia expandida sobre python y jupyter notebook](https://utadeoeduco0-my.sharepoint.com/:u:/g/personal/olmer_garciab_utadeo_edu_co/ETTmzDrvd5FBt43XoYvU6lAB5m0-kbbfzHjroIwBIhp8rg?e=VIawsl)